INSERT INTO books (title, author, explanation, img, meetingDate) VALUES ('공정하다는 착각', '마이클 샌델', '"지금 서 있는 그 자리, 정말 당신의 능력 때문인가?"<br>샌델, 기울어진 사회구조 이면에 도사린 "능력주의의 덫"을 해체하다', '/img/book/공정하다는 착각.jpeg', '2022-11-09');
INSERT INTO books (title, author, explanation, img, meetingDate) VALUES ('서울 자가에 대기업 다니는 김 부장 이야기 시리즈', '송희구', '2021년 대한민국 직장생활과 부동산에 관한<br>현실을 적나라하게 표현한 하이퍼리얼리즘 스토리', '/img/book/김 부장 이야기.jpeg', '2022-11-30');
INSERT INTO books (title, author, explanation, img, meetingDate) VALUES ('선량한 차별주의자', '김지혜', '선량한 마음만으로 평등은 이루어지지 않는다!', '/img/book/선량한 차별주의자.jpeg', '2022-12-14');
INSERT INTO books (title, author, explanation, img, meetingDate) VALUES ('데미안', '헤르만 헤세', '불안한 젊음에 바치는 헤르만 헤세의 영혼의 이야기!', '/img/book/데미안.jpeg', '2023-01-12');
INSERT INTO books (title, author, explanation, img, meetingDate) VALUES ('침묵은 여자가 되나니', '팻 바커', '신화를 재해석한 작품들이 빠지는 함정을 절묘하게 피하며<br>완성된 또 하나의 모던클래식', '/img/book/침묵은 여자가 되나니.jpeg', '2023-02-02');
INSERT INTO books (title, author, explanation, img, meetingDate) VALUES ('불안', '알랭 드 보통', '우리는 왜 불안한가?<br>불안을 어떻게 극복할 것인가?', '/img/book/.jpeg', '2023-03-08');
INSERT INTO books (title, author, explanation, img, meetingDate) VALUES ('명상록', '마르쿠스 아우렐리우스', '삶이란 전쟁터에서 끊임없이 사람들에게<br>도전과 위로를 주는 2000년간의 스테디셀러!', '/img/book/불안.jpeg', '2023-04-05');
INSERT INTO books (title, author, explanation, img, meetingDate) VALUES ('심판', '베르나르 베르베르', '죽고 난 다음에 시작되는 특별한 심판', '/img/book/심판.jpeg', '2023-05-12');
INSERT INTO books (title, author, explanation, img, meetingDate) VALUES ('내가 틀릴 수도 있습니다', '비욘 나티코 린데블라드', '숲속의 현자가 전하는 마지막 인생 수업', '/img/book/내가 틀릴 수도 있습니다.jpeg', '2023-06-25');
INSERT INTO books (title, author, explanation, img, meetingDate) VALUES ('2030 축의 전환', '마우로 기옌', '새로운 부와 힘을 탄생시킬 8가지 거대한 물결', '/img/book/2030 축의 전환.jpeg', '2023-08-16');
INSERT INTO books (title, author, explanation, img, meetingDate) VALUES ('소피의 세계', '요슈타인 가아더', '소설로 읽는 철학', '/img/book/소피의 세계.jpeg', '2023-09-20');
INSERT INTO books (title, author, explanation, img, meetingDate) VALUES ('달러구트 꿈 백화점', '이미예', '잠들어야만 입장 가능한 꿈 백화점에서 일어나는<br>비밀스럽고도 가슴 뭉클한 판타지 소설', '/img/book/달러구트.jpeg', '2023-11-14');