const Sequelize = require('sequelize');
const env = process.env.NODE_ENV || 'development';
const config = require(__dirname + '/../config/config.json')[env];
const Book = require('./book');
const Member = require('./member');
const Attend = require('./attend');
const Review = require('./review');
const Folder = require('./folder');
const List = require('./list');
const DoneFolder = require('./donefolder');
const DoneList = require('./donelist');
const Favorite = require('./favorite');
const TTPD = require('./ttpd');
const HFC = require('./hfc');
const HMC = require('./hmc');
const KFC = require('./kfc');
const KMC = require('./kmc');
const KPOP = require('./kpop');
const POP = require('./pop');
const Quote = require('./quotes');
const RecordsChoice = require('./recordsFavorite');

const db = {};
const sequelize = new Sequelize(config.database, config.username, config.password, config);

db.sequelize = sequelize;
db.Book = Book;
db.Member = Member;
db.Attend = Attend;
db.Review = Review;
db.Folder = Folder;
db.List = List;
db.DoneFolder = DoneFolder;
db.DoneList = DoneList;
db.Favorite = Favorite;
db.TTPD = TTPD;
db.HFC = HFC;
db.HMC = HMC;
db.KFC = KFC;
db.KMC = KMC;
db.KPOP = KPOP;
db.POP = POP;
db.Quote = Quote;
db.RecordsChoice = RecordsChoice;

Book.init(sequelize);
Member.init(sequelize);
Attend.init(sequelize);
Review.init(sequelize);
Folder.init(sequelize);
List.init(sequelize);
DoneFolder.init(sequelize);
DoneList.init(sequelize);
Favorite.init(sequelize);
TTPD.init(sequelize);
HFC.init(sequelize);
HMC.init(sequelize);
KFC.init(sequelize);
KMC.init(sequelize);
KPOP.init(sequelize);
POP.init(sequelize);
Quote.init(sequelize);
RecordsChoice.init(sequelize);

Book.associate(db);
Member.associate(db);
Review.associate(db);
Book.associate(db);
Member.associate(db);
Folder.associate(db);
List.associate(db);
DoneList.associate(db);
Favorite.associate(db);
Quote.associate(db);

module.exports = db;
